export const START_SEARCHING = "START_SEARCHING";
export const SEARCHING_SUCCESS = "SEARCHING_SUCCESS";
export const SEARCHING_ERROR = "SEARCHING_ERROR";
export const CLEAR_DATA = "CLEAR_DATA";

export const WORKOUT_LOC_ADDED="WORKOUT_LOC_ADDED";
export const TYPE_WORKOUT_ADDED = "TYPE_WORKOUT_ADDED";
export const INCLUDED_CARDIO = "INCLUDED_CARDIO";
export const INCLUDED_CORE = "INCLUDED_CORE";

export const START_FETCH_TYPE = "START_FETCH_TYPE";
export const FETCH_TYPE_SUCCESS = "FETCH_TYPE_SUCCESS";
export const FETCH_TYPE_ERROR = "FETCH_TYPE_ERROR";

export const BACK_PAGE = "BACK_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const RESET_PAGE = "RESET_PAGE";
export const ADD_HEADERS = "ADD_HEADERS";
export const CHANGE_CARDIO_HEADER = "CHANGE_CARDIO_HEADER";
export const CHANGE_BODY_HEADER = "CHANGE_BODY_HEADER";
export const CHANGE_CORE_HEADER = "CHANGE_CORE_HEADER";

export const RESET = "RESET";

export const WORK_LOC_ERROR = "WORK_LOC_NOT_PRESENT";
export const WORK_TYPE_ERROR = "WORK_TYPE_NOT_PRESENT";
export const FORM_ERROR = "FORM_ERROR";
