export const START_SEARCHING = "START_SEARCHING";
export const SEARCHING_SUCCESS = "SEARCHING_SUCCESS";
export const SEARCHING_ERROR = "SEARCHING_ERROR";
export const CLEAR_DATA = "CLEAR_DATA";

export const WORKOUT_LOC_ADDED="WORKOUT_LOC_ADDED";
export const TYPE_WORKOUT_ADDED = "TYPE_WORKOUT_ADDED";
export const INCLUDED_CARDIO = "INCLUDED_CARDIO";
export const INCLUDED_CORE = "INCLUDED_CORE";

export const START_FETCH_TYPE = "START_FETCH_TYPE";
export const FETCH_TYPE_SUCCESS = "FETCH_TYPE_SUCCESS";
export const FETCH_TYPE_ERROR = "FETCH_TYPE_ERROR";

export const BACK_PAGE = "BACK_PAGE";
export const NEXT_PAGE = "NEXT_PAGE";
export const RESET_PAGE = "RESET_PAGE";
export const ADD_CARDIO_HEADER = "ADD_CARDIO_HEADER";
export const ADD_BODY_HEADER = "ADD_BODY_HEADER";
export const ADD_CORE_HEADER = "ADD_CORE_HEADER";
